// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'joke_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

FTJokeModel _$FTJokeModelFromJson(Map<String, dynamic> json) {
  return FTJokeModel(
    json['id'] as String,
    json['type'] as String,
    json['text'] as String,
    json['user_id'] as String,
    json['name'] as String,
    json['profile_image'] as String,
    json['created_at'] as String,
    json['create_time'] as String,
    json['passtime'] as String,
    json['love'] as String,
    json['hate'] as String,
    json['comment'] as String,
    json['repost'] as String,
    json['bookmark'] as String,
    json['bimageuri'] as String,
    json['voiceuri'] as String,
    json['voicetime'] as String,
    json['voicelength'] as String,
    json['status'] as String,
    json['theme_id'] as String,
    json['theme_name'] as String,
    json['theme_type'] as String,
    json['videouri'] as String,
    json['videotime'] as String,
    json['original_pid'] as String,
    json['cache_version'] as int,
    json['cai'] as String,
    json['top_cmt'] as List,
    json['weixin_url'] as String,
    json['image0'] as String,
    json['image2'] as String,
    json['image1'] as String,
    json['cdn_img'] as String,
    json['is_gif'] as String,
    json['width'] as String,
    json['height'] as String,
    json['tag'] as String,
    json['t'] as int,
    json['ding'] as String,
    json['favourite'] as String,
    json['playcount'] as String,
  );
}

Map<String, dynamic> _$FTJokeModelToJson(FTJokeModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'type': instance.type,
      'text': instance.text,
      'user_id': instance.user_id,
      'name': instance.name,
      'profile_image': instance.profile_image,
      'created_at': instance.created_at,
      'create_time': instance.create_time,
      'passtime': instance.passtime,
      'love': instance.love,
      'hate': instance.hate,
      'comment': instance.comment,
      'repost': instance.repost,
      'bookmark': instance.bookmark,
      'bimageuri': instance.bimageuri,
      'voiceuri': instance.voiceuri,
      'voicetime': instance.voicetime,
      'voicelength': instance.voicelength,
      'status': instance.status,
      'theme_id': instance.theme_id,
      'theme_name': instance.theme_name,
      'theme_type': instance.theme_type,
      'videouri': instance.videouri,
      'videotime': instance.videotime,
      'original_pid': instance.original_pid,
      'playcount': instance.playcount,
      'cache_version': instance.cache_version,
      'cai': instance.cai,
      'top_cmt': instance.top_cmt,
      'weixin_url': instance.weixin_url,
      'image0': instance.image0,
      'image2': instance.image2,
      'image1': instance.image1,
      'cdn_img': instance.cdn_img,
      'is_gif': instance.is_gif,
      'width': instance.width,
      'height': instance.height,
      'tag': instance.tag,
      't': instance.t,
      'ding': instance.ding,
      'favourite': instance.favourite,
    };
